[functions]
  directory = "netlify/functions"
  [functions."get-daily-share-post"]
   	 # This schedule runs at 8:00 AM UTC every day.
   	 schedule = "0 6 * * *"
  [functions."get-daily-share-post-afternoon"]
     schedule = "0 19 * * *"



