[functions]
  directory = "netlify/functions"
	[functions."get-daily-share-post"]
   	 # This schedule runs at 9:00 AM UTC every day.
   	 schedule = "0 9 * * *"
	[functions."get-daily-share-post_X"]
   	 # This schedule runs at 9:00 AM UTC every day.
   	 schedule = "0 9 * * *"
