[functions]
  directory = "netlify/functions"
     	# This schedule runs at 9:00 AM UTC every day.
   	 [functions."get-daily-share-post"]
   	 # This schedule runs at 9:00 AM UTC every day.
   	 schedule = "0 14 * * *"
